// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsdG3Mk8GBL2QaVidVJLHD_kRJhhuQhY0',
    appId: '1:428528352300:web:36f3991695b0ec6cc4e589',
    messagingSenderId: '428528352300',
    projectId: 'everrest-1a452',
    authDomain: 'everrest-1a452.firebaseapp.com',
    storageBucket: 'everrest-1a452.appspot.com',
    measurementId: 'G-5NTR8CREK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3JGUmGTERPfLaQerXpd51vCklFWHQZnY',
    appId: '1:428528352300:android:a091b55cbf098bdbc4e589',
    messagingSenderId: '428528352300',
    projectId: 'everrest-1a452',
    storageBucket: 'everrest-1a452.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxH_1Fo9hNNCLlantjaEwEL_PdGWVT_jE',
    appId: '1:428528352300:ios:08d5aec67a6f61fdc4e589',
    messagingSenderId: '428528352300',
    projectId: 'everrest-1a452',
    storageBucket: 'everrest-1a452.appspot.com',
    iosBundleId: 'com.example.everRest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxH_1Fo9hNNCLlantjaEwEL_PdGWVT_jE',
    appId: '1:428528352300:ios:8ade99cca9f392fcc4e589',
    messagingSenderId: '428528352300',
    projectId: 'everrest-1a452',
    storageBucket: 'everrest-1a452.appspot.com',
    iosBundleId: 'com.example.everRest.RunnerTests',
  );
}
